LINEAGE_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRzUnSMbwWOyKb83-Ww6dhZR7P1849YEub-HegsdPOocTHKGbfpfx2OIMx5HiECricVZYhPzDWZ2Crk/pub?output=csv"

OVERALL_FILENAME = "Lineage.svg"
BATCH_DIRECTORY = "Lineage_batches"
BATCH_SIZE = 30
BATCH_OVERLAP_RINGS = 1

STARTING_MEMBER = "Darren Swenson"
MEMBERS_PER_RING = 6
SPIRAL_DIRECTION = -1
FIRST_RING_RADIUS = 150
RING_SPACING = 140
CIRCLE_GAP = 20

CIRCLE_SIZE = 50
DRAWING_PADDING = 40
DRAWING_BACKGROUND_COLOR = "#111827"

OFFICER_FILL_COLOR = "#94a3b8"
RETURNING_MASTER_FILL_COLOR = "#3b82f6"
PAST_MASTER_FILL_COLOR = "#1e40af"
APPOINTEE_LINE_COLOR = "#d1d5db"
MASTER_STROKE_COLOR = "#d4af37"
CURVE_APPOINTEE_LINES = True
APPOINTEE_CURVE_OFFSET = 80
APPOINTEE_CURVE_MIN_DISTANCE = 250

CIRCLE_STROKE_WIDTH = 3
APPOINTEE_LINE_WIDTH = 4
CONSECUTIVE_TERM_LINE_WIDTH = 10

FONT_COLOR = "white"
FONT_SIZE = "12px"
FONT_FAMILY = "Arial, sans-serif"
FONT_WEIGHT = "bold"
NAME_MAX_CHARACTERS_PER_LINE = 12
NAME_LINE_HEIGHT = 14
YEAR_FONT_SIZE = "10px"
YEAR_LINE_HEIGHT = 12
